# Generated by Django 2.2 on 2019-06-08 12:00

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='Sizes',
            new_name='Size',
        ),
    ]
