# Generated by Django 2.2 on 2019-06-08 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20190608_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='size',
            new_name='name',
        ),
    ]
