# Generated by Django 2.2 on 2019-06-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20190609_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='itemId',
            field=models.ManyToManyField(blank=True, related_name='orders', to='menu.Item'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='topping',
            field=models.ManyToManyField(blank=True, related_name='orders', to='menu.Topping'),
        ),
    ]
