# Generated by Django 2.2 on 2019-06-23 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_category_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='orderId',
        ),
        migrations.AddField(
            model_name='orderline',
            name='orderId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.Order'),
            preserve_default=False,
        ),
    ]
