# Generated by Django 2.2 on 2019-06-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_auto_20190629_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
