# Generated by Django 2.2 on 2019-06-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_auto_20190630_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='itemId',
        ),
        migrations.AddField(
            model_name='orderline',
            name='itemId',
            field=models.ManyToManyField(blank=True, related_name='orderItems', to='menu.Item'),
        ),
        migrations.RemoveField(
            model_name='orderlinetopping',
            name='topping',
        ),
        migrations.AddField(
            model_name='orderlinetopping',
            name='topping',
            field=models.ManyToManyField(blank=True, related_name='orderToppings', to='menu.Topping'),
        ),
    ]
