# Generated by Django 2.2 on 2019-06-30 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_auto_20190630_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='itemId',
        ),
        migrations.AddField(
            model_name='orderline',
            name='itemId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderItems', to='menu.Item'),
        ),
        migrations.RemoveField(
            model_name='orderlinetopping',
            name='topping',
        ),
        migrations.AddField(
            model_name='orderlinetopping',
            name='topping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderToppings', to='menu.Topping'),
        ),
    ]
