# Generated by Django 2.2 on 2019-07-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_auto_20190630_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
