# Generated by Django 2.2 on 2019-07-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_orderline_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='itemSize',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
